### ISSUE TITLE
Jovian cannot handle certain input filenames

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#112]
Will complete with more information later, for now:

**Problem:**
Samples with naming schemes like "*.R[1|2].*" are handled incorrectly. The "." is not anticipated in the regex (since our machines don't output files with that naming scheme) and therefore the sample_sheet.yaml isn't populated (i.e. empty). The following error is reported:

```
Files in input directory (raw_data/) are present
Generating sample sheet...
Traceback (most recent call last):
  File "bin/generate_sample_sheet.py", line 47, in <module>
    main(parser.parse_args())
  File "bin/generate_sample_sheet.py", line 37, in main
    sample = samples.setdefault(match.group(1), {})
AttributeError: 'NoneType' object has no attribute 'group'
```

**Solution:**
Update the regex in `bin/generate_sample_sheet.py` to `(.*)[_.]R?(1|2)(?:_.*\.|\..*\.|\.)f(ast)?q(\.gz)?`.

**_Update:_** Nope, not the solution :rofl: (I`ll pick this up when I'm back at the RIVM)

Note to self --> Test case = ENNGS

**Comment by florianzwagemaker** [comment]
This should be solved in https://github.com/DennisSchmitz/Jovian/commit/b2d4882d565db6811643bc9dc328f2f6d3932bc8

The regex has been changed in order to support a `.` in the filename structure.

The fastqc wrapper has been slightly modified to not cause downstream issues with the filename change. Should look for a solution that's a bit more "clean", but this should work in the meantime as it is fairly consistent.
