### ISSUE TITLE
The script `database_updater.sh` is incorrect on Ubuntu

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#147]
When performing `bash jovian -id` the updating goes correctly on either CentOS, RHEL and Ubuntu. At the end of this process a script named `~/database_updater.sh` is generated to facilitate `crontab` automatic updates.

When you check that file, the following and correct code is generated on CentOS and RHEL:
```
for file in *.dmp;
        do awk '{gsub("\t",""); if(substr($0,length($0),length($0))=="|") print substr($0,0,length($0)-1); else print $0}' ${file} > ${file}.delim; done
```

This is generated on Ubuntu:
```
tar -xzf new_taxdump.tar.gz
    for file in *.dmp; do awk '{gsub("\t",""); if(substr(bin/includes/Databases_installer,length(bin/includes/Databases_installer),length(bin/includes/Databases_installer))=="|") print substr(bin/includes/Databases_installer,0,length(bin/includes/Databases_installer)-1); else print bin/includes/Databases_installer}' < typeoftype.dmp > typeoftype.dmp.delim; done
```

For now, the fix is easy, manually edit those faulty lines of code with the correct excerpt above.

Maybe because `awk` and/or HEREDOC work differently on the different distros?

**Comment by DennisSchmitz** [comment]
Ok, maybe it has nothing to do with Ubuntu but something else... On the laptop (Ubuntu) it works fine... TBD

**Comment by florianzwagemaker** [comment]
See https://github.com/DennisSchmitz/Jovian/tree/Issue147 (https://github.com/DennisSchmitz/Jovian/commit/0c5038e53f97942bfb7fd4c58960a3b410f06093)

Something interesting:
As noted in the earlier comments, we found this issue on a Ubuntu server but this didn't exist on Ubuntu on WSL.

The Ubuntu laptop ran WSL1. However, when running this script in Ubuntu on WSL2, then the issue comes up again.
At this moment the only key difference that could have an impact between these WSL versions is the virtualization.

Should test on CentOS/RHEL 7+ anyways to see if the behaviour is as expected.

**Comment by florianzwagemaker** [comment]
Should be fixed by https://github.com/DennisSchmitz/Jovian/pull/152

tested on both Ubuntu and CentOS and the script worked without issue with the commits in said pullreq.
