### ISSUE TITLE
Difficulties in installing Jovian helper environment

### ISSUE THREAD

**Issue by tengfei-emory** [DennisSchmitz/Jovian_archive#177]
Dear developer,

Thank you for developing this tool. I am trying to install Jovian on a Linux server. I managed to install Jovian master environment (and the dependencies by -ic), while I could not install Jovian helper. Basically, the installer was stuck at "solving environment" for several hours, before skipping to installing databases which also failed. I would like to ask if there can be any solutions to it. Thanks again for your help.

**Comment by DennisSchmitz** [comment]
Dear Teng Fei,

Due to holiday I could not reply promptly, sorry. Regarding your question... The SARS2 pandemic caused a lot of extra work for the developers and maintainers of Jovian. Therefore it has not had the updates and maintenance it required to remain stable, especially in regards to external databases and their APIs, as your issue indicates. We are currently working on a new version of the pipeline where we focused more on maintainability by using containers. I hope to have that version out soon (tm). I will update this issue when it becomes publicly available.

My sincere apologies for the inconvenience this causes and I hope your are able and willing to wait for the update.

Sincerely,
Dennis
