### ISSUE TITLE
IGVjs html files are empty (404 error).

### ISSUE THREAD

**Issue by thierryjanssens** [DennisSchmitz/Jovian_archive#48]
The IGVjs_index.html file is made but the links result in a 404 Not Found error.
The respective IGNjs files are there but only contain the header: Alignments from a BAM file.

**Comment by DennisSchmitz** [comment]
This is a bug caused by how we implemented `nginx` and it occurs in a multi-user setting. Sadly, there is no quick fix.

The problem is that `nginx` is started from within a certain user's `jovian_master` master environment. So then any symlinks must be created by that user. Solutions we've found would require `sudo` rights, and therefore they are not portable... So if anyone knows how to fix it I`m all ears. 

For now though, I'll generate the required symlinks and then it should work.

**Comment by thierryjanssens** [comment]
The IGVjs_index.html file is now correctly referring to the right files (404 Not found error has disappeared).
Still, the respective IGNjs files are just 3 KB and only contain the header: Alignments from a BAM file. 
Does the nginx analysis take a while (i.e. > 3 hours), per chance?

**Comment by DennisSchmitz** [comment]
The html file is indeed very small, all it contains are links to the actual files and their indices. Nginx doesn't do any analysis, it just streams data to you, IGVjs does all the work. Are you by chance opening a very large/high-coverage contig? Because if so, that's a known issue for which there is no solution unless opening it on a computer with more RAM.

**Comment by thierryjanssens** [comment]
They are all empty (also after re-running the respective rule):

(Jovian_master) [janssetk@rivm-biohn-l01p scaffolds_filtered]$ ls -lshrt *.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.0K May 14 01:11 4311801289_S6_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.1K May 14 01:22 BL-GLY-medium_S12_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.1K May 14 01:35 Undetermined_S0_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.0K May 14 01:44 4311900021_S10_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.0K May 14 01:48 4311900027_S11_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.0K May 14 01:54 4311801284_S5_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.0K May 14 02:06 4311801293_S7_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.0K May 14 02:22 4311801270_S3_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.0K May 14 02:49 4311801295_S8_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.0K May 14 03:59 4311801297_S9_L001_IGVjs.html
34K -rwxrwxrwx 1 janssetk Domain Users 3.0K May 14 09:55 4311801280_S4_L001_IGVjs.html

**Comment by thierryjanssens** [comment]
Inside these files are links to the respective fasta, bam, etc... files, however.

**Comment by thierryjanssens** [comment]
They do not seem to get rendered.

**Comment by DennisSchmitz** [comment]
Probably found it, can you please remove all htmls via `rm data/scaffolds_filtered/*.html` and `rm results/IGVjs_index.html` and try again?

Please let me know if that works because then I`ll push a bugfix.

**Comment by thierryjanssens** [comment]
@DennisSchmitz You mean rerunning the wrapper after deletion of the html files without cloning the latest version of Jovian?

**Comment by DennisSchmitz** [comment]
Yes. Because then I know if e5da1bc is the right fix.

**Comment by thierryjanssens** [comment]
This has not worked.
From within the Notebook_report the IGVjs_index.html the 404 error remains. The  sample_IGVjs.html files contain links to bam, fasta and other files. The hash used between the the index and the respective files is the same (CuI6dLMl2krt76cAwRZ4nDRGyCqQBfIq).

**Comment by DennisSchmitz** [comment]
Sat down with Thierry and fixed it.

**Problem:** 
_N.B. It only occurs on a multi-user setting, not in a single-user setting_
It's due to having multiple users trying to visualize scaffolds with `IGVjs` (via `nginx`) simultaneously (different datasets) via the same port (default = 8083). If two or more people are trying to visualize data via the same port (e.g. 8083), only the first user "owns" the `nginx` process running on that port and can stream data, all the others get a '404 error'.

**Solution/work-around:** The "owner"/username of the `nginx` process on the specified port (default = 8083) needs to generate the sym-link to the dataset ('mv /to/dataset/location/Jovian/` then `bash bin/set_symlink.sh`). 

This is a problem we need to discuss with the IT and bioinformatics department. We somehow need to have a range of available ports for different users. But then how do we manage all that without `sudo` rights?

**Comment by florianzwagemaker** [comment]
The issue with NGINX is solved in https://github.com/DennisSchmitz/Jovian/commit/217ea4e453e56380d0a10df65ac8fa8a8bfc00e6 
It is however required to restart NGINX on both computing headnodes with these new settings before it can work. This can only be done by the **owner** of the nginx processes on the respective computing nodes.

This fix has been implemented on computing headnode 2 (graphic interface headnode) for our local system, headnode 1 still uses the old method in which this issue still exists. If you wish to analyze the data in IGVjs then use computing headnode 2 for the time being until we push v0.9.3 as an independent release.

**Comment by DennisSchmitz** [comment]
Fixed in dev 0.9.3 branch, closing

**Comment by thierryjanssens** [comment]
Also in v0.9.4 the IGV htmls files are not rendered in the Notebook_report (initially they were).
The issue seems not to be solved.

**Comment by DennisSchmitz** [comment]
Could you provide more data? Like did you use default settings? Do you have a demo dataset? And if under identical settings sometimes they are rendered and other times not, did you change anything in your user configurations?

**Comment by thierryjanssens** [comment]
Seems to be solved again in v0.9.5-dev .

**Comment by thierryjanssens** [comment]
The problem with the scaffold viewer not displaying/rendering the IGV plots persists in v0.9.5-dev.

**Comment by thierryjanssens** [comment]
Perhaps the following may be indicative for the reason of the problem:

Cleaning up...
	Removing empty folders...
	Removing temporary files...
	Creating symlinks for the interactive genome viewer...
chmod: cannot operate on dangling symlink ‘/tmp/etc/nginx/default-site/G90WwuiJwn9mrNUPEl9xkZjC3LoLetQi’
chmod: cannot operate on dangling symlink ‘/tmp/etc/nginx/default-site/kcArRMtW8WkIEEFI9opkqviwyGGqivkW’
chmod: cannot operate on dangling symlink ‘/tmp/etc/nginx/default-site/SOEuTzG7NWUizbFwcuJ4xmD9ygGLBXNx’
chmod: cannot operate on dangling symlink ‘/tmp/etc/nginx/default-site/R9nYNitgv6VMWhOU73RNPDLdtEUqWxih’

**Comment by florianzwagemaker** [comment]
what URLs are present in the IGVjs html file? To which hostnames are they pointing and from which server are you trying to view the data?

The URLs for IGVjs must be the same hostname as the hostname from which you're trying to view the data (through jupyter). If these hostnames do not match then 404 and/or forbidden errors will be presented.

If you're running an analysis on server A and wish to view the results on server B, then run `bash jovian --archive` on the server of analysis and run ` bash jovian --rebuild-archive` on the server where your Jupyter process is running.

This cannot be changed on a short-term because of our local computing setup

**Comment by thierryjanssens** [comment]
The hostname from the terminal the analysis was run from and the Notebook were created:

[janssetk@rivm-biohn-l02p Jovian]$ $ hostname -A
rivm-biohn-l02p.int.ssc-campus.nl 

Snippet from the 

[janssetk@rivm-biohn-l02p Jovian]$ less results/IGVjs_index.html 

 "http://rivm-biohn-l02p.int.ssc-campus.nl:8083/xsmr4JaFdAdo8hVy9Nly7XdHHhNrjk9G/Jovian/data/scaffolds_filtered/4311801193_S3_L001_IGVjs.html"

**Comment by DennisSchmitz** [comment]
@thierryjanssens wasn't this fixed now? This was the one where the analysis was started from the wrong conda environment, right?

**Comment by DennisSchmitz** [comment]
Update for people reading this later later and getting scared... It is due to a complicated local setup (multiple head-nodes on a grid system), this will not occur in a normal setup.

**Comment by thierryjanssens** [comment]
It is fixed (somehow, but I do not know how).
No, the analyses were started from the correct conda environment,
