### ISSUE TITLE
rulegraph with wrapper

### ISSUE THREAD

**Issue by thierryjanssens** [DennisSchmitz/Jovian_archive#58]
When trying to deploy the rulegraph creation with the Jovian wrapper an error is spit out. Probably this has to do with the header section of the rulegraph file (the verbose part of the wrapper output?).

```
(Jovian_master) [janssetk@rivm-biohn-l02p Jovian]$ bash jovian --rulegraph -i raw_data/ | dot -Tpng > rulegraph.png

Error: <stdin>: syntax error in line 1 near 'Files'
Warning: syntax ambiguity - badly delimited number '.9.' in line 8 of <stdin> splits into two tokens
Warning: syntax ambiguity - badly delimited number '.2.' in line 8 of <stdin> splits into two tokens
Warning: syntax ambiguity - badly delimited number '1.0.' in line 10 of <stdin> splits into two tokens

When you take alook at the rulegrap file th wrapper out put is on top. Probably this casues the error?

(Jovian_master) [janssetk@rivm-biohn-l02p Jovian]$ head rulegraph -n 25
Files in input directory (raw_data/) have .fastq format
Generating sample sheet...
Succesfully generated the sample sheet


######################################################################
All pre-flight checks of Jovian have been completed
You are using Jovian version v0.9.2.1
Please keep in mind that this pipeline is still a work-in-progress
It is expected that several portions are unstable until release 1.0.0
######################################################################


Starting snakemake
Unique identifier for this Jovian run is: G1jHIgaQr6uCYmxCSyZgTJmJYnWv1K4I 
digraph snakemake_dag {
    graph[bgcolor=white, margin=0];
    node[shape=box, style=rounded, fontname=sans,                 fontsize=10, penwidth=2];
    edge[penwidth=2, color=grey];
	0[label = "all", color = "0.61 0.6 0.85", style="rounded"];
	1[label = "HuGo_removal_pt2_extract_paired_unmapped_reads", color = "0.28 0.6 0.85", style="rounded"];
	2[label = "HuGo_removal_pt3_extract_unpaired_unmapped_reads", color = "0.22 0.6 0.85", style="rounded"];
	3[label = "De_novo_assembly", color = "0.31 0.6 0.85", style="rounded"];
	4[label = "SNP_calling", color = "0.56 0.6 0.85", style="rounded"];
	5[label = "Fragment_length_analysis", color = "0.64 0.6 0.85", style="rounded"];




```

**Comment by DennisSchmitz** [comment]
When an analysis is finished it should automatically be generated (in the snakemake report in the results/ folder). And otherwise you can see the rulegraph on the git repo.

Can't really see why it doesn't work though, will look into it. As a workaround, try 'snakemake --profile profile' --rulegraph | dot (etc) '

**Comment by thierryjanssens** [comment]
I cannot see it in the results/ folder. I understand that I need to run the report notebook first.
(Now I know how to run jupyter notebook from the rivm-biohn-l02p... https://rivm-bioinformatica.slack.com/team/UFEC1391C). 


But 

snakemake --profile profile' --rulegraph | dot (etc)

cannot be used.The samplesheet is needed, whichs is created by the wrapper.

**Comment by DennisSchmitz** [comment]
This command works for me `snakemake --profile profile --rulegraph | dot -Tpng > delme.png`

If you want to generate the samplesheet manualy do `bash bin/generate_sample_sheet.py ${INPUT_DIR} > sample_sheet.yaml`. But looking at your error log, the sample_sheet was successfully generated, so it should be present.

About the `--rulegraph` not working with the wrapper, this is indeed because of the extra printed text from the wrapper. `dot` apparently reads all input. I'll look into it later, but it has no priority because you can see the `rulegraph` on the homepage of the repo, and otherwise you can generate it with the instructions above.
