### ISSUE TITLE
Add a shell wrapper

### ISSUE THREAD

**Issue by DennisSchmitz** [DennisSchmitz/Jovian_archive#7]
_Merged with #6. Related to #4._

**Priority: High**

It's already in development, will add it to the repo soon. But it should contain the following flags...
- `dry-run` --> snakemake's `-n` flag
- `unlock` --> snakemake's `--unlock` flag (in case the pipeline crashes expectantly)
- `clean` --> remove all pipeline output (folders: `data/` `results/` `logs/`)
- `install-dependencies` --> snakemake's `--use-conda` & `--create-envs-only` options
- `install-IGVjs` --> link to IGVjs install script
- `generate-sample-sheet` --> link to sample sheet script

It will also include the code of #4 , and it will check if `Jovian_master` and `Jovian_helper` are available and will otherwise install them. It also allows specifying Snakemake arguments in the wrapper instead of using a profile file (which contains our in-house grid settings).

In a later version this will be added:

Automated installation scripts for:
  - `download-dbs` --> link to database download/install scripts
  - `configure-jup` --> link to Jupyter NB configuration scripts
  - `archive-results` --> zip all output files and their respective sample-sheet and log files (audit trail)

**Comment by florianzwagemaker** [comment]
### Automatic installation of (mini)conda

When running the wrapper through `sh jovian` or `bash jovian`, a new subshell is spawned as defined by `#!/bin/bash` at the start of the wrapper. All changes to the environment are local to the subshell and only to the subshell.

Altering the PATH through `export PATH=${HOME}/tmp/Miniconda3/bin:$PATH` therefore only affects the subshell instead of the "real" shell.

This can be circumvented by running `source jovian` instead of using `sh` or `bash`. **requires strict mode to be turned off with `#set -euo pipefail`**
Can we update the readme and other guides to match?

Error of the miniconda installer below is fixed in commit https://github.com/DennisSchmitz/Jovian/commit/ca025a3953bfaf60f71dc0af73ce0d991b6b8ce3
> Please run using "bash" or "sh", but not "." or "source"\nlatest: line 14: return: can only `return' from a function or sourced script

**Comment by florianzwagemaker** [comment]
> When running the wrapper through `sh jovian` or `bash jovian`, a new subshell is spawned as defined by `#!/bin/bash` at the start of the wrapper. All changes to the environment are local to the subshell and only to the subshell.
> 
> Altering the PATH through `export PATH=${HOME}/tmp/Miniconda3/bin:$PATH` therefore only affects the subshell instead of the "real" shell.
>
> This can be circumvented by running `source jovian` instead of using `sh` or `bash`. **requires strict mode to be turned off with `#set -euo pipefail`**
> Can we update the readme and other guides to match?

Solved in commit https://github.com/DennisSchmitz/Jovian/commit/01370591d44f58268525ebd0f1374086d3eb4500
Jovian wrapper can now run succesfully with `bash jovian`.
`sh jovian` *should* work but this is untested.

In either case it is still required to have strict mode turned off in the wrapper `#set -euo pipefail` (line 2 of the wrapper).

Export to PATH isn't completely functional as it should be. Temporary workaround with echoing the PATH into .bash_profile.

Missing `fi` statement in commit https://github.com/DennisSchmitz/Jovian/commit/01370591d44f58268525ebd0f1374086d3eb4500 has been fixed in https://github.com/DennisSchmitz/Jovian/commit/7b9767137947e2b63f192908f4e5be302100983f

**Comment by DennisSchmitz** [comment]
See issue #18 , needs to be added to the `new_taxdump` db installer code.

**Comment by florianzwagemaker** [comment]
Wrapper requires restructuring.

In the current setup of the wrapper (commit https://github.com/DennisSchmitz/Jovian/commit/0b347fcf80bb16b8102223155c1a0f476605f9e4 ), it is not possible to use a command like `bash jovian -h` without first installing conda and the respective conda environments.

This is undesired since commands like `-h / --help` should always be accessible without having to go through the installation process

**Edit**: First version of restructure in commit https://github.com/DennisSchmitz/Jovian/commit/ec72b6910f7c98841d664f6ab636a8017b3318d2

**Comment by florianzwagemaker** [comment]
Writing conda to PATH is changed in https://github.com/DennisSchmitz/Jovian/commit/0af9ba5e51d1dfdca2b536bb3c3ea79b52d2605f

PATH is now written to `~/.bashrc` instead of `~/.bash_profile` for compatibility as not all systems or linux-operating systems use `~/.bash_profile` by default and this can result in complications when using the wrapper on a system that is not our own.

**Comment by florianzwagemaker** [comment]
As quickly referenced in #27 
Updated wrapper is tested on both a clean Ubuntu installation as a clean CentOS (rhel) installation through docker.

Current version (https://github.com/DennisSchmitz/Jovian/commit/a5422afc56a5c59f77c6747465b92962ffe7326a) should be good for release 0.9.1 of Jovian.

## Functions
Through the various commits, the following functions were built in:
- Shows help when the `-h` flag or `--help` flag is submitted
- Interactive installation of miniconda if conda doesn't exist
- Adding miniconda to PATH when this is accepted by user
- Interactive installation of Jovian_master environment
- Automatic switching to the Jovian_master environment
- Installation of IGVjs when the `-ii` flag is submitted
- Checks if the `~/.ncbirc` file is present (important for BLAST)
- Installation of pipeline conda environments when the `-ic` flag is submitted
- Shows Snakemake help when the `-sh` flag is submitted
- Allows specification of input directory with the `-i` flag
- Checks if the input directory specified exists
- Checks the file extensions in the input directory and generates a sample sheet accordingly
- Starts snakemake when all checks have completed and includes user arguments
- Generates a single archive with the generated data and results when the `--archive` flag is submitted
- Cleans up generated data and results when the `--clean` flag is submitted

## Requirements
The requirements of Jovian are significantly simplified through this wrapper, Jovian only requires the following 4 dependencies to be present on a system in order to run:
- git
- curl
- bzip2
- which

Most systems have these dependencies installed already. However, if these dependencies are missing they can be installed through the following commands:
**Ubuntu:** `sudo apt-get install git curl bzip2 which -y`
**CentOS:** `sudo yum install git curl bzip2 which -y`
Sudo rights are required to run these commands, if you don't have these rights then check with your system administrator for the dependencies above.

## Usage
Download Jovian to your directory of choice with the commands below:
`cd <path/to/your/working/directory>` & `git clone https://github.com/DennisSchmitz/Jovian.git` 
Enter the newly created directory with `cd Jovian/`

Copy your to-be-analyzed files to a directory within the Jovian directory, for example "input".
Run Jovian with `bash jovian -i input/`, replace "input/" with the directory in which your fastq (or gzipped fastq) files are present.

Jovian will now run the "pre-flight" checks to see if everything is good-to-go, once done the pipeline will start with analyzing your files.

**Note: Jovian can only run as a non-root user.**
