### ISSUE TITLE
SVG export

### ISSUE THREAD

**Issue by thierryjanssens** [DennisSchmitz/Jovian_archive#80]
I cannot export scaffold viewer plots as an svg when using the Saver SVG button:

Selected port for NGINX is: 8083 
chmod: changing permissions of ‘/tmp/etc/nginx/default-site/tQ9tjN37XQmNxB1uz9TG08vZJLQfH3lI’: Permission denied

**Comment by DennisSchmitz** [comment]
I also get these errors messages after the server update en reboot in the week of the 21st of July. I've never tried the export SVG function though, I get it at startup. Don't think it's a pipeline problem since I've not seen it before that time, looks more like a permission problem. Would you mind contacting IT about it?

And just to be sure, you have performed the analysis yourself right?

**Comment by DennisSchmitz** [comment]
After updating IGVjs to v2.3.5 for issue #98, it now seems to work. This fix will be included in the next release.
